server:
  port: 8888


spring:
  application:
    name: confServer
  cloud:
    config:
      server:
        git:
          uri: http://github.com/ZARAYACH/cofig.git
          clone-on-start: true
          default-label: master
  security:
    user:
      password: root
      name: root